services:
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    env_file:
      - .env
      - workflows/.env
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - N8N_EDITOR_BASE_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
      - NODE_FUNCTION_ALLOW_BUILTIN=https,http,url,querystring,path,os
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - NODES_EXCLUDE=[]
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
    volumes:
      - /docker/appdata/n8n/data:/home/node/.n8n
      - /docker/appdata/n8n/local-files:/files
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sbin/zpool:/sbin/zpool:ro
      - /dev/zfs:/dev/zfs:ro
      - /data:/data:ro
    networks:
      - shared_net

networks:
  shared_net:
    external: true
